### PR TITLE
Update progress

### PR DESCRIPTION
**Pull request by richlander**
/cc @terrajobst, @ellismg, @akoeplinger

### CODE REVIEW

**Comment by akoeplinger** [comment]
LGTM :+1: Any updates on getting this automated (https://github.com/dotnet/corefx-progress/issues/9) ?

**Comment by richlander** [comment]
The problem is that the script isn't reliable. We could invest more in that, but haven't chosen to yet, given other priorities. I know its frustrating. Thanks for your patience.

**Comment by akoeplinger** [comment]
Understood, would be great if you could run the script manually every week instead :)

**Comment by ellismg** [comment]
I put a reminder on my calendar.

**Comment by akoeplinger** [comment]
Thanks @ellismg !

**Comment by richlander** [comment]
@ellismg, @terrajobst - want to take a quick look and merge?

**Pull request merged**
